from __future__ import annotations

from datetime import datetime
from pathlib import Path

import openpyxl
import pandas as pd

from trading_bot.excel.strategy_tab import ensure_strategy_tab


def export_backtest_workbook(source_workbook: Path, trades_df: pd.DataFrame, strategy_dict: dict, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    workbook = openpyxl.load_workbook(source_workbook)
    strategy_ws = ensure_strategy_tab(workbook)
    _write_strategy_snapshot(strategy_ws, strategy_dict)
    _write_system_rows(workbook["System"], trades_df)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    target = output_dir / f"SwingPlanner_backtest_{timestamp}.xlsx"
    workbook.save(target)
    return target


def _write_strategy_snapshot(ws, strategy_dict: dict) -> None:
    row = ws.max_row + 2 if ws.max_row >= 2 else 2
    ws.cell(row=row, column=1, value=f"bt-{datetime.now().strftime('%H%M%S')}")
    ws.cell(row=row, column=2, value=strategy_dict.get("name"))
    ws.cell(row=row, column=3, value="PDF backtest dashboard")
    ws.cell(row=row, column=4, value=False)
    ws.cell(row=row, column=5, value=strategy_dict.get("timeframe"))
    ws.cell(row=row, column=6, value=strategy_dict.get("direction"))
    ws.cell(row=row, column=7, value=strategy_dict.get("strategy_style", "custom"))
    ws.cell(row=row, column=8, value="Generated by dashboard export")
    ws.cell(row=row, column=9, value=f"Target {strategy_dict.get('risk_reward_ratio')}:1 or stop/max hold")
    ws.cell(row=row, column=10, value=f"{strategy_dict.get('stop_loss_pct')}% below entry")
    ws.cell(row=row, column=11, value=f"{strategy_dict.get('risk_reward_ratio')}:1 RR")
    ws.cell(row=row, column=12, value=strategy_dict.get("notes", ""))
    ws.cell(row=row, column=13, value=datetime.now().strftime("%Y-%m-%d %H:%M"))


def _write_system_rows(ws, trades_df: pd.DataFrame) -> None:
    start_row = 19
    max_rows = 31
    rows = trades_df.head(max_rows).to_dict("records")
    for offset, trade in enumerate(rows):
        row = start_row + offset
        ws.cell(row=row, column=1, value=trade["market_trend"])
        ws.cell(row=row, column=2, value=trade["symbol"])
        ws.cell(row=row, column=3, value="N/A")
        ws.cell(row=row, column=4, value=trade["entry_point"])
        ws.cell(row=row, column=5, value="N/A")
        ws.cell(row=row, column=6, value="N/A")
        ws.cell(row=row, column=7, value=trade["avg_volume"])
        ws.cell(row=row, column=8, value=trade["macd_crossover"])
        ws.cell(row=row, column=9, value=trade["ema_crossover"])
        ws.cell(row=row, column=10, value=trade["price_position"])
        ws.cell(row=row, column=11, value=trade["bullish_reversal"])
        ws.cell(row=row, column=12, value=trade["entry_date"])
        ws.cell(row=row, column=13, value=trade["stop_loss"])
        ws.cell(row=row, column=14, value=trade["entry_price"])
        ws.cell(row=row, column=15, value=trade["target_price"])
        ws.cell(row=row, column=16, value=trade["quantity"])
        ws.cell(row=row, column=17, value=trade["confidence"])
        ws.cell(row=row, column=18, value=trade["exit_price"])
        ws.cell(row=row, column=19, value=trade["exit_date"])
        ws.cell(row=row, column=22, value=trade["comments"])
